### ISSUE TITLE
Sample code uses incorrect Type

### ISSUE THREAD

**Issue by sirtopas** [mariusmuntean/ChartJs.Blazor#113]
Current code uses `XAxes` but should be `xAxes`
https://github.com/mariusmuntean/ChartJs.Blazor/blob/4d99fa55f4cd18de7151e9d8a5bc13d07ebe7365/samples/Shared/ChartJs.Blazor.Sample.Shared/Components/LineChart/TimeLineChartComponent.razor#L74

**Comment by Joelius300** [comment]
Why do you think it should be `xAxes`?

**Comment by sirtopas** [comment]
I don't, it was the only way the code compiled without error.

**Comment by Joelius300** [comment]
You're probably using the nuget on version 1.1.0 right?

The code on master is the current code, the code which will be released in the future. To browse the code for the 1.1.0 release, check out the [corresponding tag](https://github.com/mariusmuntean/ChartJs.Blazor/tree/v1.1.0). There you'll find it use `xAxes`.

**Comment by Joelius300** [comment]
Is it confusing that the samples on master aren't for the current nuget-release? On a demo-site, I'd understand that the samples need to be adjusted for the current stable version but is that the same for the repository?

I'm not sure if I'm thinking about this correctly, What do you think?

cc @mariusmuntean

**Comment by Joelius300** [comment]
I just updated the readme to comply with the latest release again. Unlike the samples (can be argued about), the readme should definitely only contain stuff for the latest release and not the development version on master.
