### ISSUE TITLE
How to Reload chart as documented in quick start?

### ISSUE THREAD

**Issue by erikhaverkamp** [mariusmuntean/ChartJs.Blazor#125]
### Describe your question
In the quick start manual the following is described:

_currently the chart might disappear if you navigate away from it and then come back. My remedy is to just call the chart's Reload() method in the page's OnAfterRender() method. A PR that fixes this permanently would make me very happy._

I would like to know how you call a Reload on the chart. I can't find the method?

Thanks, Erik

**Comment by Joelius300** [comment]
You shouldn't need to worry about that bug anymore, it's been fixed quite a while ago. If you still experience that bug, please file an issue with all the details you have so we can investigate.  
As you might have seen by the last-modified date, our wiki is unfortunately horribly outdated.

You should refer to the readme, it's the most up-to-date resource we currently provide.

@mariusmuntean should we remove the wiki until we have the time to do a more elaborate one?

**Comment by erikhaverkamp** [comment]
Ok, thanks for helping me out. I must have done something else wrong. I will close this.

Erik
