### ISSUE TITLE
Any environment other than development fails to load JavaScript resources

### ISSUE THREAD

**Issue by lyptt** [mariusmuntean/ChartJs.Blazor#132]
### Describe the bug
When specifying ASPNETCORE_ENVIRONMENT as a value other than development, you get 404 errors for the ChartJs _content resources.

### Which Blazor project type is your bug related to?
- Server-Side

### Which charts does this bug apply to?
all charts

### To Reproduce
1. Using this version of ChartJSBlazor '1.1.0'.
2. [With this code](https://github.com/mariusmuntean/ChartJs.Blazor#usage).
3. Run `ASPNETCORE_ENVIRONMENT=production dotnet run` from the project root, or use the VSCode run task in the sample project
4. See error.

### Expected behavior
The scripts load successfully

### Screenshots
<img width="876" alt="Screenshot 2020-06-14 at 15 55 37" src="https://user-images.githubusercontent.com/346710/84596767-854c9d80-ae57-11ea-9628-ea4f1c349eff.png">

### Additional context / logging
```batch
[2020-06-14T14:50:17.862Z] Information: Normalizing '_blazor' to 'https://localhost:5001/_blazor'. blazor.server.js:1:5212
Loading failed for the <script> with source “https://localhost:5001/_content/ChartJs.Blazor/moment-with-locales.min.js”. localhost:5001:76:1
Loading failed for the <script> with source “https://localhost:5001/_content/ChartJs.Blazor/Chart.min.js”. localhost:5001:79:1
Loading failed for the <script> with source “https://localhost:5001/_content/ChartJs.Blazor/ChartJsBlazorInterop.js”. localhost:5001:82:1
[2020-06-14T14:50:18.046Z] Information: WebSocket connected to wss://localhost:5001/_blazor?id=FHaTttdw29shyxT33frTkQ. blazor.server.js:1:5212
[2020-06-14T14:50:18.462Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. blazor.server.js:15:27309
[2020-06-14T14:50:18.464Z] Information: Connection disconnected. blazor.server.js:1:5212
```
### Code example
[a.zip](https://github.com/mariusmuntean/ChartJs.Blazor/files/4776650/a.zip)

**Comment by Joelius300** [comment]
Thanks for the report.

This seems strange. I'm assuming that's not actually the issue.

I've downloaded the repro project and saw that the "StaticWebAssets.xml" file contains the path `/Users/rhys/.nuget/packages/chartjs.blazor/1.1.0/build/../staticwebassets/`. When building it on my own machine, I could see that both for the release and the debug build, the path stays the same.

I can reproduce the issue without specifying any environment e.g. by just executing the a.exe when building in both release and debug (which will use the default environment "Production").

This issue doesn't seem to be related to the environment at all. Maybe it has something to do with https? You probably need to investigate a bit further.

Ps. Is there another nuget with static assets where this issue does not occur in the same repro project?

**Comment by lyptt** [comment]
I don't think it's a HTTPS thing because HTTPS works absolutely fine with the development configuration. I'm not sure how to further simplify the test case unfortunately. All I know is that this library for me only works in development mode, and no other environment works.

**Comment by Joelius300** [comment]
HTTPS was just a guess because I'm not familiar with the https-redirect that asp.net provides. I'll try to repro the issue from scratch, it seems you just used the default template is that correct?

**Comment by lyptt** [comment]
Yeah that's right, everything's taken from the readme, no further changes were made.

**Comment by Joelius300** [comment]
Can confirm that it's not an HTTPS issue. Creating a new server-side blazor application with the default template and following the readme results in the error when running the compiled application (debug or release) with a non-development environment.  
However, I highly doubt that this is an issue with our library. The assets will stay the same no matter the environment. I'm assuming this is the expected behaviour for running the build directly without publishing but I currently have no proof (e.g. docs paragraph or GitHub issue) to support that claim.

I'm assuming you're not debugging the application when you want to run it in production mode so the easy workaround is to publish the app before running it. This way the `wwwroot` folder is generated which contains all the linked static assets.

**Comment by lyptt** [comment]
Yeah, sounds like it could be a ASP.NET issue in that case. Normally I don't debug apps on another environment mode, but we're setting up a brand new environment at the moment which is how I noticed the issue. I'll raise a ticket in the ASP.NET repo and see if that goes anywhere.

Thanks for the help!

**Comment by Joelius300** [comment]
No worries, maybe I'll try to find some more infos using a different library.

As an aside, could you link your issue here?

**Comment by lyptt** [comment]
Found this issue which seems to indicate it's by design, with a reasonable workaround:

https://github.com/dotnet/aspnetcore/issues/20409

**Comment by Joelius300** [comment]
Awesome, thank you 👍
