### ISSUE TITLE
ChartExamples:  An unhandled error has occurred.

### ISSUE THREAD

**Issue by win32nipuh** [mariusmuntean/ChartJs.Blazor#136]
I run the ChartExamples project and receive in the browser

Loading...
An unhandled error has occurred. Reload 🗙
and Page source

`

<!DOCTYPE html>
  | <html>
  |  
  | <head>
  | <meta charset="utf-8" />
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  | <title>Chart Samples</title>
  | <base href="/Blazor-ApexCharts/" />
  | <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
  | <link href="css/app.css" rel="stylesheet" />
  | </head>
  |  
  | <body>
  | <app>Loading...</app>
  |  
  | 
  | <script type="text/javascript">
  | // Single Page Apps for GitHub Pages
  | // https://github.com/rafrex/spa-github-pages
  | // Copyright (c) 2016 Rafael Pedicini, licensed under the MIT License
  | // ----------------------------------------------------------------------
  | // This script checks to see if a redirect is present in the query string
  | // and converts it back into the correct url and adds it to the
  | // browser's history using window.history.replaceState(...),
  | // which won't cause the browser to attempt to load the new url.
  | // When the single page app is loaded further down in this file,
  | // the correct url will be waiting in the browser's history for
  | // the single page app to route accordingly.
  | (function (l) {
  | if (l.search) {
  | var q = {};
  | l.search.slice(1).split('&').forEach(function (v) {
  | var a = v.split('=');
  | q[a[0]] = a.slice(1).join('=').replace(/~and~/g, '&');
  | });
  | if (q.p !== undefined) {
  | window.history.replaceState(null, null,
  | l.pathname.slice(0, -1) + (q.p \|\| '') +
  | (q.q ? ('?' + q.q) : '') +
  | l.hash
  | );
  | }
  | }
  | }(window.location))
  | </script>
  | 
  |  
  | <div id="blazor-error-ui">
  | An unhandled error has occurred.
  | <a href="" class="reload">Reload</a>
  | <a class="dismiss">🗙</a>
  | </div>
  |  
  |  
  | <script src="_framework/blazor.webassembly.js"></script>
  | <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
  | <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
  | </body>
  |  
  | </html>
 

`

How to fix it and run the samples?

**Comment by Joelius300** [comment]
`Blazor-ApexCharts`? This is `ChartJs.Blazor` not `Blazor-ApexCharts` nor patrick. You probably want to report this issue to [joadan/Blazor-ApexCharts](https://github.com/joadan/Blazor-ApexCharts) :)

**Comment by win32nipuh** [comment]
I am very sorry!!!!! :-D
