### ISSUE TITLE
How to get the stacked bar chart to always have y-axis start at zero?

### ISSUE THREAD

**Issue by jpeaveytrendswell** [mariusmuntean/ChartJs.Blazor#141]
### Describe your question
How to get the stacked bar chart to always have y-axis start at zero?

### Which Blazor project type is your question related to?

- Server-Side

### Which charts is this question related to?
StackedBarChart

### JavaScript equivalent
this might be an older version, new to all this...
var options = {
    yAxes: [{
        ticks: {
            min: 0,
            max: 100,
            stepSize: 20
        }
    }]
}

**Comment by SeppPenner** [comment]
I haven't tested this, but something like

```razor
_config = new BarConfig
        {
            Options = new BarOptions
            {
                Title = new OptionsTitle
                {
                    Display = true,
                    Text = "Sample chart from Blazor"
                },
                Scales = new BarScales
                {
                    XAxes = new List<CartesianAxis>
                    {
                        new LinearCartesianAxis
                        {
                            BarThickness = BarThickness.Flex,
                            Stacked = true,
                            Ticks = new LinearCartesianTicks
                            {
                                StepSize = 20,
                                BeginAtZero = true,
                                SuggestedMax = 100
                            }
                        }
                    }
                },
                Responsive = true
            }
        };
```

References:
* https://github.com/mariusmuntean/ChartJs.Blazor/blob/283666c4ee06b25845cfd53ec55d45e5bbc51fcc/src/ChartJs.Blazor/ChartJS/Common/Axes/Ticks/LinearCartesianTicks.cs
* https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/src/ChartJs.Blazor/ChartJS/BarChart/Axes/BarLinearCartesianAxis.cs
* https://github.com/mariusmuntean/ChartJs.Blazor/blob/915a9803c82052d638ff08aa364d204ba3c76bf2/src/ChartJs.Blazor/ChartJS/Common/Axes/CartesianAxis.cs
* https://github.com/mariusmuntean/ChartJs.Blazor/blob/751354fa3e1def65af2275ab2861e2e09b96f741/samples/Shared/ChartJs.Blazor.Sample.Shared/Components/BarCharts/StackedBarChartComponent.razor

**Comment by Joelius300** [comment]
Good pointers @SeppPenner.

You can use the `BeginAtZero` property of the `Ticks` property of your axis. If you need more control over the minimum and maximum value, you can set the `Min` and `Max` as well as many others on the `Ticks` property of your axis. 

I don't know your scenario but assuming you want a linear y-axis, you can use code like this (this goes inside the initialization of your `BarScales` object for the `Scales` property - see [this sample](https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/samples/Shared/ChartJs.Blazor.Sample.Shared/Components/BarCharts/SimpleBarChartComponent.razor) for more):

```csharp
YAxes = new List<CartesianAxis>
{
    new BarLinearCartesianAxis
    {
        Ticks = new LinearCartesianTicks
        {
            BeginAtZero = true
        }
    }
}
```
or (the JavaScript example ported)
```csharp
YAxes = new List<CartesianAxis>
{
    new BarLinearCartesianAxis
    {
        Ticks = new LinearCartesianTicks
        {
            Min = 0,
            Max = 100,
            StepSize = 20
        }
    }
}
```

Please reopen if this doesn't answer your question :)

**Comment by jpeaveytrendswell** [comment]
Hi Joel;

Thanks for the response. Yes, I found it on your side bar chart and was able to achieve what I wanted.

Thanks again, I do appreciate the support!

Joe

**Comment by jpeaveytrendswell** [comment]
Hi Hans;

You are the man!

Thanks so much 😉
Joe

**Comment by SeppPenner** [comment]
Glad to know that we could help you :)
