### ISSUE TITLE
TimePoint is missing

### ISSUE THREAD

**Issue by papunov** [mariusmuntean/ChartJs.Blazor#146]
Hello, 

I am using version 1.1.0 installed via NuGet. TimePoint is missing in the following namespace ChartJs.Blazor.ChartJS.Common.Time. 

Could you please check and fix it?

Thanks!

Br,
Nikolay Papunov

**Comment by Joelius300** [comment]
Do you mean `TimeTuple`?

**Comment by papunov** [comment]
I would like to create line chart with Datetime for x. I saw the sample code in the repo and there TimePoint was used. I can see the class in the repo as well but not in the NuGet. If the new method is to use TimeTuple, I am fine to use it. Could you please provide quick sample?

**Comment by Joelius300** [comment]
As mentioned in [the readme](https://github.com/mariusmuntean/ChartJs.Blazor#a-word-on-the-samples)

> Unlike the documentation, the samples should always be up to date with the current development on master. That means, that the code you see in the samples folder on master might not actually compile on the current nuget version. To browse the samples for the latest nuget version, see the [samples on the releases branch](https://github.com/mariusmuntean/ChartJs.Blazor/tree/releases/samples).

So [here](https://github.com/mariusmuntean/ChartJs.Blazor/blob/releases/samples/Shared/ChartJs.Blazor.Sample.Shared/Components/LineChart/TimeLineChartComponent.razor)'s the time line chart one.

**Comment by Joelius300** [comment]
Btw, please see #122 in regards to the samples.
