### ISSUE TITLE
Charts does not render color by using a different culture

### ISSUE THREAD

**Issue by alessandro-gargiulo** [mariusmuntean/ChartJs.Blazor#147]
### Describe the bug
I'm using ChartJs.Blazor on a multi-language UI.
The UI language is chosen by using the CookieRequestCultureProvider.
When using culture "en-US" colors on charts display properly.
When change culture to "it-IT" colors on charts does not render properly: they were display by using a gray scale. 

### Which Blazor project type is your bug related to?
- Server-Side

### Version of ChartJs.Blazor
v.1.1.0

### Which charts does this bug apply to?
In the repro there is **ChartJsPieChart**, but this behaviors happen also to the **ChartJsLineChart**

### To Reproduce
Use this repository to reproduce the issue: https://github.com/alessandro-gargiulo/ChartJs-GreyColor-Repro
1) Switch language to English.
2) Switch language to Italian.

### Expected behavior
The colors are rendered correctly as they are rendered by using English culture.

**Comment by Joelius300** [comment]
Thank you for the report and repro project. I'm surprised that not more people have run into this. I discovered it a while back and hope to have fixed it (see 960016ff) but unfortunately, this commit isn't included in the Version 1.1.0 you're using. I suggest you upgrade to latest preview version ([2.0.0-preview1](https://www.nuget.org/packages/ChartJs.Blazor/2.0.0-preview1)) which should fix the issue.

Please report back if it worked :)

**Comment by alessandro-gargiulo** [comment]
Sorry for late response.
I have tried with the 2.0.0-preview1 and this fix the problem. Thank you.
