### ISSUE TITLE
Horizontal barchart doesn't show any bars

### ISSUE THREAD

**Issue by enricoreich** [mariusmuntean/ChartJs.Blazor#15]
Hello,

I use latest feature/CleanupAndRefactorings branch and as far as I know it works really good but the horizontal barchart does not show any bars. You also can see it at your demo website.

**Comment by mariusmuntean** [comment]
Hi Enrico,

I'm aware of that bug but I don't have a good idea why that might be the case. Can't promise that version 0.9.0 (I'm currently preparing to release it) will fix the horizontal barchart.

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
This issue is now fixed as you can see in the [live sample](https://www.iheartblazor.com/HorizontalBarChart).
