### ISSUE TITLE
Preparing Release 0.9.0

### ISSUE THREAD

**Issue by mariusmuntean** [mariusmuntean/ChartJs.Blazor#16]
Increase version numbers
Extend documentation on how to use the library in client- and server-side projects
Credit the people who's PR were merged

**Comment by Joelius300** [comment]
Seeing as [release 1.0.1](https://github.com/mariusmuntean/ChartJs.Blazor/releases/tag/Release-1.0.1) (including [nuget-package](https://www.nuget.org/packages/ChartJs.Blazor/1.0.1)) is out, I'm closing this issue.
