### ISSUE TITLE
ArgumentOutOfRangeException when data is removed from sample charts

### ISSUE THREAD

**Issue by mmuffins** [mariusmuntean/ChartJs.Blazor#167]
When running the sample project, an exception is thrown if the 'Remove Data' button is clicked after all data points were already removed from a chart. This seems to affect all charts that have this functionality.

### Which Blazor project type is your bug related to?
- Server-Side

### Which charts does this bug apply to?
All charts in the sample project that have the add/remove data functionality.

### To Reproduce
1. Build and run the current master version of the project
2. Open the basic line chart (or any other chart that has a Remove Data button)
3. Click the Remove Data button until all data has been removed from the chart
4. Click the button once more
5. An ArgumentOutOfRangeException is thrown

### Expected behavior
No exception should occur

**Comment by Joelius300** [comment]
Oh wow, that's embarrassing 😅 

I specifically took care of this error for removing datasets because this was an issue with the last sample-version. But that made me miss the other one, oops.

**Comment by mmuffins** [comment]
Yeah, that happens. I pushed an update to #165 which should fix the samples. After the patch I wasn't able to crash any of the samples.
