### ISSUE TITLE
launchSettings.json being overwritten after adding package

### ISSUE THREAD

**Issue by LeeStevens318** [mariusmuntean/ChartJs.Blazor#175]
### Describe the bug
After adding the package my `launchSettings.json` keeps being overwritten on every build

### Which Blazor project type is your bug related to?
- Client-Side

### Which charts does this bug apply to?
N/A

### To Reproduce
1. Using this version of ChartJs.Blazor.Fork 2.0.1, tried with 2.0.0 same result.
2. Build project

### Expected behavior
No changes to the `launchSettings.json`

#### Correct:
![BlazorCorrect](https://user-images.githubusercontent.com/28816427/104145211-45b05900-541a-11eb-9b6d-541ee4f9f0dc.png)

#### Overwritten to:
![BlazorWrong](https://user-images.githubusercontent.com/28816427/104145222-4ba63a00-541a-11eb-80d6-6e8ef4e321bd.png)

**Comment by Joelius300** [comment]
Thanks for the report!

This isn't a new issue at all but somehow I've never encountered it before and no one has reported it until now 🤔  
Anyhow, I've published [2.0.2](https://github.com/mariusmuntean/ChartJs.Blazor/releases/tag/v2.0.2) to fix this.

The [nuget](https://www.nuget.org/packages/ChartJs.Blazor.Fork/2.0.2) should be up any second.

**Comment by LeeStevens318** [comment]
TY, this has resolved the issue.
