### ISSUE TITLE
Could not find 'ChartJsInterop.setupChart

### ISSUE THREAD

**Issue by LeiYangGH** [mariusmuntean/ChartJs.Blazor#193]
### Describe the bug
I can clone the git repo and run the samples, but when include and run in my own project, got exception.

### Which Blazor project type is your bug related to?
- Server-Side

### Which charts does this bug apply to?
ChartJs.Blazor.LineChart

### To Reproduce
1. ChartJs.Blazor.Fork 2.0.2 install by nuget
2. Copy almost all code from https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/ChartJs.Blazor.Samples/Client/Pages/Charts/Line/Basic.razor.
3. only the data is made my own. 
```csharp
LineDataset<int> dataset1 = new LineDataset<int>(my own list<int>)
```
4. See error.

### Expected behavior
Can run and show chart.

Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Could not find 'ChartJsInterop.setupChart' ('ChartJsInterop' was undefined).
Error: Could not find 'ChartJsInterop.setupChart' ('ChartJsInterop' was undefined).
    at http://localhost:5000/_framework/blazor.server.js:1:67713
    at Array.forEach (<anonymous>)
    at e.findFunction (http://localhost:5000/_framework/blazor.server.js:1:67673)
    at v (http://localhost:5000/_framework/blazor.server.js:1:69415)
    at http://localhost:5000/_framework/blazor.server.js:1:70361
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.server.js:1:70334)
    at http://localhost:5000/_framework/blazor.server.js:1:26441
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:5000/_framework/blazor.server.js:1:26411)

**Comment by LeiYangGH** [comment]
sorrty i missed some js.

**Comment by ghost** [comment]
Hi @LeiYangGH 
I am getting the same error,
what js were you missing?

**Comment by LeiYangGH** [comment]
> Hi @LeiYangGH
> I am getting the same error,
> what js were you missing?

At least this: <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>

**Comment by perlun** [comment]
For reference, we are seeing something similar to this after upgrading our project to .NET 9 but _only_ for local development, with Visual Studio or Rider. In the deployed version of the app, things work fine. 🤔
