### ISSUE TITLE
I get an error when I use it in my project (nuget package)

### ISSUE THREAD

**Issue by larshg** [mariusmuntean/ChartJs.Blazor#2]
I have created a small test example here:
https://github.com/larshg/ChartJSTest

It won't compile due to this error:
 Pages\Index.cshtml(13,38,13,45): error CS0029: Cannot implicitly convert type 'Microsoft.AspNetCore.Blazor.ElementRef' to 'ChartJs.Blazor.Charts.ChartJsLineChart'

Do you think its an error on your side or on the Blazor side?

On a side node: the paramters Config, Width and Height is shown in red, as opposed to ref which is in purple.

In your project and Sample project they are all purple - but maybe there is a difference between using the nuget package and referencing the project directly?

Regards, Lars

**Comment by mariusmuntean** [comment]
Hi Lars,

you need to add `@addTagHelper *,ChartJs.Blazor` to your _ViewImports.cshtml file to get VS support and to ge the thing to build.
According to Microsoft this won't be necessary for the first stable release.

Please also refer to the Getting Started guide from the WiKi
