### ISSUE TITLE
Chart does not show

### ISSUE THREAD

**Issue by martinmichaelsen** [mariusmuntean/ChartJs.Blazor#20]
Running the NugetDemo1.Demo does not show the BubblesChart. The reason for this perhaps simple complaint is that I cannot for the life of me get a simple Blazor App to display a simple ChartJS.Blazor chart. So I tried the above Demo project and it demonstrates the same problem.
The large sample does work however but I cannot see why and what the difference might be.
My claim is. A new Blazor app with the Nuget Pack and the edits in _ViewImports cannot display any chart.

**Comment by realbronto** [comment]
Had the same problem, see my PR for the solution: 
https://github.com/mariusmuntean/ChartJs.Blazor/pull/19

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
The workaround for the client-side blazor issue described in the readme (using a `ReferenceConverter` variable) solves the same issue as the linker added in #19 but in a less nice way (additional unused variable(s)). I didn't understand it when I started to work on the library again but I'm almost certain now that the linker would be the better approach to solve this issue. Therefore I think we should pick this issue back up, implement it in our samples and add instructions to the readme as well as the getting-started page.

CC  @mariusmuntean

**Comment by Joelius300** [comment]
This issue was resolved and the linker is now in use again (was closed in #53). The solution to this issue is also described in the readme.
