### ISSUE TITLE
error RZ9978: The directives @addTagHelper, @removeTagHelper and @tagHelperPrefix are not valid in a component document.

### ISSUE THREAD

**Issue by Venando-a** [mariusmuntean/ChartJs.Blazor#24]
After updating a solution from blazor 0.7 to 0.9 and ChartJs.Blazor to  0.91 I get this error thrown: `error RZ9978: The directives @addTagHelper, @removeTagHelper and @tagHelperPrefix are not valid in a component document. Use '@using <namespace>' directive instead.`

I think the getting started instructions need updating as this is what I have implemented: 
`3. Now you need to help VS a bit by adding this line @addTagHelper *,ChartJs.Blazor to _ViewImports.cshtml.`

**Comment by larshg** [comment]
Yes, the documentation is not up-to-date with the new preview4 release. @mariusmuntean do  you have time to look trough the PRs and maybe make a new release?

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
This is fixed in the readme but the [wiki](https://github.com/mariusmuntean/ChartJs.Blazor/wiki/Getting-Started) is still outdated. I have added a [todo](https://github.com/mariusmuntean/ChartJs.Blazor/projects/3#card-28660006) to the backlog. This issue will be closed once that todo is done.

**Comment by Joelius300** [comment]
I emptied the wiki for now.
