### ISSUE TITLE
small issue with doughnut chart demo

### ISSUE THREAD

**Issue by 274188A** [mariusmuntean/ChartJs.Blazor#26]
https://www.iheartblazor.com/doughnutchart

hit update repeatedly to see what happens...

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
There is no more update-button in the live sample. Does this issue still occur? If so, please add some details on how to reproduce it. Otherwise you can just close this issue :)

**Comment by Joelius300** [comment]
Closing this because no response was given after one month. Feel free to reopen if necessary.
