### ISSUE TITLE
Zoom and pan support

### ISSUE THREAD

**Issue by alexgubanow** [mariusmuntean/ChartJs.Blazor#30]
Hello, as I understood currently here is no zooming or panning. Is there in plan to implement? Is iot possible to implement it at all?

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
What do you mean by zooming and panning? Are you talking about [this chart.js extension](https://github.com/chartjs/chartjs-plugin-zoom) or something nativ to chart.js?

We might add support for some plugins later but we have a lot of other stuff to tackle first :)

**Comment by Joelius300** [comment]
Closing this because no response was given for two months. Feel free to reopen if necessary.
