### ISSUE TITLE
Apply changes from non-forked repo

### ISSUE THREAD

**Issue by Joelius300** [mariusmuntean/ChartJs.Blazor#32]
Because I want to use this awesome library in a personal project of mine I downloaded the sources. I wasn't able to find the TimeAxis and there were many errors when updating everything to the latest previews. 
For this reason I only copied the source of the actual library and worked on it (fix all the preview errors, lots of refactoring, add lots of properties which are supported by chartJs, ..). 

Problem is, I didn't think about giving my adjustments back to the community. I really want to help with this awesome project but I don't know how I can transfer my commits and changes to a pull request here since it's not a fork and has a different folder structure.
I'm currently working on the TimeAxis which I have seen being requested so maybe there's interest for that. It's almost done and as I said, I'd love to let you include it in this repos.

One thing to keep in mind is that I have manually done some of the currently suggested pull request.
The ones I have (partly) done:
 - [Fixed tooltips and added MaintainAspectRatio](https://github.com/mariusmuntean/ChartJs.Blazor/pull/17) (but already changed because of a better way of implementing string and object enums)
 - [Update to preview6](https://github.com/mariusmuntean/ChartJs.Blazor/pull/31) (but now already updated to preview8)
 - [Don't add wrong generatelabelsfunc](https://github.com/mariusmuntean/ChartJs.Blazor/pull/18) (but I don't know the difference as I have not experienced any issues without this change)

Another thing to keep in mind is that I'm almost only working on the Linechart and thus only really testing those properties. I have however reworked a lot of inheritance trees and options which are used for other charts as well. There shouldn't be any sideeffects but it's not tested like most of the library. It seems as many properties that are currently in the master branch weren't tested as well because some simply have the wrong name or are in the wrong place.

Does anyone know how you could import my changes without just copying the code and commiting all at once?

EDIT: my non-forked copy of this repo is [here](https://github.com/Joelius300/ChartJSBlazor).

**Comment by SeppPenner** [comment]
I guess, this can be closed since the migration process is already in preparation: https://github.com/Joelius300/ChartJSBlazor/issues/97.
