### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by fabulousduck** [mariusmuntean/ChartJs.Blazor#33]
After having installed the package using the dotnet CLI 

`dotnet add package ChartJs.Blazor --version 0.9.0-preview`

it started throwing the following error

`Program.cs(12,23): error CS0433: The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

I am running dotnet version `3.0.100-preview6-012264`

**Comment by SeppPenner** [comment]
If I was you, I would take a look at https://github.com/Joelius300/ChartJSBlazor. This project is maintained at least.

**Comment by Joelius300** [comment]
This issue should not occur anymore since we've updated the library to the non-preview versions where this doesn't apply anymore. If you still experience this problem, please reopen this issue :)
