### ISSUE TITLE
Compatibility with core 3 preview 9 or/and soon release

### ISSUE THREAD

**Issue by maythamfahmi** [mariusmuntean/ChartJs.Blazor#37]
I have tried this lib with core 3 preview 9, get lot of errors and I assume it is not compatible.

Is there plans for release a version that is compatible with core 3?

**Comment by Joelius300** [comment]
Currently this library is not compatible with preview9. If you want to use a compatible version, take a look at [my extension of this library](https://github.com/Joelius300/ChartJSBlazor).

## Disclaimer
I'm not trying to compete with this library. At the time I wanted to use this library, it was not compatible with the preview I was using so I copied the source and adjusted it. It has now grown a lot and fixed many bugs. It's currently maintained and compatible with the newest version of .net core 3. I have not gotten a response on https://github.com/mariusmuntean/ChartJs.Blazor/issues/32 so I currently don't have marius' opinion on this.
