### ISSUE TITLE
Migration: Support callbacks

### ISSUE THREAD

**Issue by SeppPenner** [mariusmuntean/ChartJs.Blazor#41]
Migrated from https://github.com/Joelius300/ChartJSBlazor/issues/55:

### Describe the feature request
We should somehow make it possible to support callbacks (e.g. https://www.chartjs.org/docs/latest/configuration/tooltip.html#tooltip-callbacks).

### Which Blazor project type is your feature request related to?
Client-Side and server side.

### Describe the solution you'd like
Support for callbacks if possible. (I don't have an idea yet how to support them...

**Comment by Joelius300** [comment]
I guess callbacks are generally supported now, just only the ones we manually program in at the time 😅   
In the future, the discover of callbacks to "translate" should be automatic but there will be a new issue for that.

The tooltip callbacks are tracked in #131
