### ISSUE TITLE
Migration: Check if the label on dataset level is needed

### ISSUE THREAD

**Issue by SeppPenner** [mariusmuntean/ChartJs.Blazor#43]
Migrated from https://github.com/Joelius300/ChartJSBlazor/issues/46:

From https://github.com/Joelius300/ChartJSBlazor/issues/40#issuecomment-519690615:

We need to investigate whether the label on dataset basis is valid for all kind of charts.

For `pie` and `doughnut`, it has no effect: https://jsfiddle.net/g1anoety/ without the datalabels plugin enabled. (I would remove this for all charts where it's not yet needed and add it again if it's needed after we managed to get https://github.com/Joelius300/ChartJSBlazor/issues/34 done).

Following https://www.chartjs.org/docs/latest/charts/:

* line: Needed, check https://jsfiddle.net/ukwsn6c2/.
* bar: Needed, check https://jsfiddle.net/ukwsn6c2/1/.
* radar: Needed, check https://jsfiddle.net/ukwsn6c2/2/.
* doughnut and pie: Not needed, check https://jsfiddle.net/g1anoety/.
* polar area: Not needed, check https://jsfiddle.net/ukwsn6c2/3/. (We need to remove this!)
* bubble: Needed, check https://jsfiddle.net/ukwsn6c2/4/.
* scatter: Needed, check https://jsfiddle.net/ukwsn6c2/5/.

I have asked the guys from Chart.Js to check this as well and tell us, what's the idea behind this: https://github.com/chartjs/Chart.js/issues/6452.

**Comment by Joelius300** [comment]
Thanks for the investigation. This will be respected in #96.

**Comment by SeppPenner** [comment]
Please see https://github.com/chartjs/Chart.js/issues/6452#issuecomment-636513726. I guess, this is deprecated now? That's how I understood it at least.

**Comment by Joelius300** [comment]
I was actually quite confused by what happened in that issue. How come it's about title now? I thought this is only about the dataset label which isn't deprecated right?

**Comment by SeppPenner** [comment]
You're right. I will ask them again.

**Comment by Joelius300** [comment]
No you don't have to.

**Comment by SeppPenner** [comment]
Ok :)

**Comment by Joelius300** [comment]
I see you already posted something, I guess it won't hurt 😅
