### ISSUE TITLE
Data.Labels has to be explicitly initialized before adding elements

### ISSUE THREAD

**Issue by mkopara** [mariusmuntean/ChartJs.Blazor#49]
### Describe the bug
It would be nice if Labels is declared without having to initialize it prior using AddRange such as here
_config.Data.Labels.AddRange(new[] {"A", "B", "C", "D"});

**Comment by Joelius300** [comment]
Thank you for the report!

This should only be the case for the charts that we've not reworked yet. What chart type(s) did you experience this issue with?
