### ISSUE TITLE
Add full TitleConfiguration

### ISSUE THREAD

**Issue by RestoreMonarchy** [mariusmuntean/ChartJs.Blazor#65]
I'd like to suggest to add full OptionsTitle support, so I can change a Title color. 
Default color looks bad on within theme and I can't change it with css.

https://www.chartjs.org/docs/latest/configuration/title.html

Thank You!

**Comment by Joelius300** [comment]
Thanks for contacting us!

Good idea, crazy how we haven't done that yet :)  
I'll look into it unless you want to do it yourself in which case, please tell us.

**Comment by RestoreMonarchy** [comment]
I'll have a look and try then make pull request. If I won't it will mean I couldn't

**Comment by Joelius300** [comment]
Yes it should be enough to just add the properties. I'm actually already done pretty much (I was already working on something) so unless you've already started, I'll just submit mine 😅

**Comment by RestoreMonarchy** [comment]
Oh well I did it too, but I'll still make a pull request, so just reject it if you already made it

**Comment by RestoreMonarchy** [comment]
Thank you for quick response! I willl close issue now.

**Comment by Joelius300** [comment]
It's been merged to master. I don't know how long it will take for the nuget to be updated. If you need the changes right now, you might need to build our library from the sources.  
I hope you understand :)
