### ISSUE TITLE
Chart not display after reload

### ISSUE THREAD

**Issue by KelvinKaYiuLok** [mariusmuntean/ChartJs.Blazor#7]
Hi,

I am trying Blazor server side with this library and it works great, however, if I navigate away from the page that contains chart and comes back, the chart disappeared. I have included the below code and still does not work according to the documentation.

    protected override void OnAfterRender()
    {
        lineChartJs.Reload();
    }

**Comment by larshg** [comment]
@KelvinKaYiuLok is this still an issue with the newest version?

**Comment by KelvinKaYiuLok** [comment]
Yes is all working now.

**Comment by larshg** [comment]
Nice, Can you close the issue then?
