### ISSUE TITLE
Change X and Y axis font color

### ISSUE THREAD

**Issue by ItsMeDan11** [mariusmuntean/ChartJs.Blazor#71]
I'm trying out the simple bar chart from the demo as a Blazor server experiment.    Looks really good, but I can't figure out how to change the colors used for the text on the axis and data labels.  Is there an example I can look to?

**Comment by Joelius300** [comment]
Thanks for contacting us!

I'm not sure what exactly you mean. As always when you don't know _how_ to do something with this library, I'd advise you to look into the [Chart.js docs](https://www.chartjs.org/docs/latest/) and play around with [their samples](https://www.chartjs.org/samples/latest/) ([sample sources](https://github.com/chartjs/Chart.js/blob/master/samples)). Once you understand how to do it with plain javascript, you can try to emulate it within this library; the location of the properties and the names should be the same (except for camel- vs PascalCasing). However it's very possible that we don't have the property that you need or we have it but it's just wrong (unfortunately there are still quite a few mistakes).

Do you have javascript code you could show me so I understand what effect you're trying to achieve? If not, could you maybe try to create an example (as code or e.g. [JSFiddle](https://jsfiddle.net)) which demonstrates your use-case?

**Comment by ItsMeDan11** [comment]
I had a little more of a chance to play around and love this library, but I still can't see where to add the color.   In javascript it would look something like this.  

  yAxes: [{
   ticks: {
     beginAtZero:true,
     fontColor: 'red'
},
 
In the bar chart I'm using, I can see the beginAtZero property, but it won't compile if I add font color property.

Here is what I have currently that works.
Axes = new List<CartesianAxis>
	{
	    new BarLinearCartesianAxis
	      {
		Ticks = new LinearCartesianTicks
		{
		     BeginAtZero = true
		}
	}
}

**Comment by Joelius300** [comment]
You're doing it right but I'm sure you're using the nuget and not the newest (inofficial) version where this is fixed. The commit 283666c4 added the missing options and fixed the inheritance. Once a new nuget releases you can use the `FontColor` property :)  
Until then you'll have to manually build the library from the newest sources and reference it.

It was already asked on gitter; I sadly don't know when a new nuget version will release. I won't close the issue but if you want you can close it already - the nuget will be updated eventually.

**Comment by ItsMeDan11** [comment]
Thanks.  I'll try that.

**Comment by steamonimo** [comment]
The current nuget release is from 12/13/2019. When will the nuget with support for the FontColor in Ticks will be released?
