### ISSUE TITLE
Suggesting minor echancements

### ISSUE THREAD

**Issue by ItsMeDan11** [mariusmuntean/ChartJs.Blazor#73]
I have been modifying my local version of ChartJs.Blazor, adding properties like 'Duration' to the ArcAnimation.   I'm not a developer (just teaching myself Blazor now) & have zero experience with Github.  Other than learning how to use Github, is there a way to contribute back to this project with the changes I've made?

**Comment by Joelius300** [comment]
Hey, thanks for being interested!

I have very limited time currently so I don't know how much I can assist you but I can give you the most basic stuff.

You can [fork the repository](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks) by clicking "Fork" in the top-right of any page of our repo (e.g. this one). This will create a clone of our repo for your account. There you can do changes as much as you want (usually you'd do that on a different branch). After you're done with the changes, you can submit a [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) to this repo. We can then review that and merge it into this repo if the changes are accepted.

I think it's best if you read [Collaborating with issues and pull requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests) from GitHub, it'll teach you everything you need to know regarding Forks and Pull Requests :)

**Comment by ItsMeDan11** [comment]
Thank you for the direction.  I have attempted to make a new fork & project with just 2 small changes and submit a pull request.  I've tested this in a pie chart and a bar chart & it is working.  Please let me know if I can improve anything for the future.
