### ISSUE TITLE
Data labels over data point

### ISSUE THREAD

**Issue by DavidStania** [mariusmuntean/ChartJs.Blazor#79]
### Describe your question
Hey Guys,
can anyone describe how to show labels over or inside data points? Sometimes it is very usefull to know witch exacly value datapoint has, without moving cursor hover for showing tooltip.

### Which Blazor project type is your question related to?
- Server-Side

### Which charts is this question related to?
all charts

**Comment by Joelius300** [comment]
Thanks for the issue.

I think for that you need the [datalabels-plugin](https://github.com/chartjs/chartjs-plugin-datalabels). As far as I understand you don't have to configure/change anything in this library for the plugin to work, just take a look at the [getting-started page](https://chartjs-plugin-datalabels.netlify.com/guide/getting-started.html).

Sometime in the future there will be an easy way to add plugins in this library and also a way to extend the classes with custom fields so you could add whatever you want if you need it (for example when you're using a plugin).

I'll close this issue for now. If this isn't enough information or you know what needs to be done for this then feel free to reopen.

**Comment by Joelius300** [comment]
FYI If you have setup the plugin, you can configure it with this library from now on (see #91). This change is not included in the latest nuget release (1.1.0) but will be published in the future.
